[package]
name = "qsis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
crossterm = "0.29.0"
csv = "1.3.1"
plotters = "0.3.7"
ratatui = "0.29.0"
